.                    === COPY PC-TALK III ===
.
.
.NOTICE - A limited license is granted to all users of this program,
.to make copies of this program and distribute them to other
.users, on the following conditions:
.
.	1. The program is not to be distributed to others in
.	modified form.
.
.	2. No fee (or other consideration) is to be charged for copying 
.	or distributing the program without an express written 
.	agreement with The Headlands Press, Inc.
.
.	3. The notice displayed at program start-up is not to be 
.	bypassed, altered, or removed.
.
.	Copyright (c) 1983 The Headlands Press, Inc.
.
.
pause
.
. *** Ready to copy...
.
. *** Make sure that the PC-TALK.III disk is in drive A
.
. *** Place a blank, FORMATTED, disk in drive B
.
pause
copy a:*.* b:
del b:pc-talk.dir
del b:pc-talk.key
del b:pc-talk.def
.
.
. *** Please make sure that you have provided a copy of the documentation
.
. *** If the file PC-TALK.DOC is on a separate disk,
.     insert that disk in drive A and type 'COPY A:*.* B:' <Enter>
.
.     Thank you for supporting ==Freeware==