.               ===PRINT PC-TALK III DOCUMENTATION===
.
.	*** The PC-TALK III documentation is 70 pages long.
.
.	(If you don't want to print the documentation now,
.	    or want to stop printing while it's in progress,
.	    press the <Ctrl> and <Break> keys at the same time.)
.
.	*** Make sure that your printer is on and loaded with
.	    continuous form paper.
.
.	*** Align the print head with the top of the first sheet.
.
.	*** Now hold down the <Ctrl> key and tap the <PrtSc> key once.
.	    Then release the <Ctrl> key.
.
pause	
TYPE PC-TALK.DOC
.
. 	*** Now press <Ctrl> and tap <PrtSc> once again,
.	    to turn off printing -- then release <Ctrl>.
.
pause
.
.	*** To run PC-TALK III...
.
.	    Place the PC-TALK III disk in drive A.
.
.	    type 'TALK64' <Enter> if you have 64K of memory
.	    type 'TALK128' <Enter> if you have 128K or more of memory
.
.	    Thank you for supporting ==Freeware==
